### ISSUE TITLE
No able to deploy to hockey using Xcode 9

### ISSUE THREAD

**Issue by maskedpear** [theappbusiness/MasterFastfile#36]
We did migrate from Xcode 8 to Xcode 9 but start seeing issues when running `deploy_to_hockey `. For some reason is trying to code sign the Cocoapods frameworks. Any help?

`[10:11:47]: ▸ === BUILD TARGET SOME_POD OF PROJECT Pods WITH CONFIGURATION Release ===
[10:11:47]: ▸ Check dependencies
[10:11:47]: ▸ Code Signing Error: SOME_POD does not support provisioning profiles. SOME_POD does not support provisioning profiles, but provisioning profile {prov profile set in TAB_PROVISIONING_PROFILE is shown here} has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor.`

**Comment by maskedpear** [comment]
I think it might be related to #33

**Comment by zacoid55** [comment]
I think you're right @maskedpear - this has come up a few times when we've been using this. Let me bring it up with the devs

**Comment by maskedpear** [comment]
Thank you. It is a kind of a blocker for us at the moment.

**Comment by zacoid55** [comment]
@maskedpear https://discuss.circleci.com/t/xcode-9-build-failures-due-to-code-signing-errors-in-pods/16713 this should solve the issue you're seeing - it's the new way Xcode 9 build system works

**Comment by zacoid55** [comment]
https://github.com/fastlane/fastlane/issues/10543 this as well, `Liaojiahao`'s answer further down

**Comment by maskedpear** [comment]
@zacoid55 we tried that already with no luck. If you read my original comment, we don't see `NO_SIGNING\` as provisioning profile but instead the name of provisioning profile specified under `TAB_PROVISIONING_PROFILE `.
Even with that block of code at the end of Podfile we still get the same error. Looks like something runs after cocoapods post_install causing it to override 'Automatic' with the actual provisioning profile

**Comment by zacoid55** [comment]
Ahhhh I apologise - we'll dig around some more

**Comment by maskedpear** [comment]
I was trying few different things but nothing solves the problem 100%. What I have for now:
- Under every subproject and the Pods project, a new user-defined variable `CODE_SIGNING_ALLOWED = NO`
- I had to override **_build_with_gym()** from MasterFile to our local Fastfile and changed `gym(export_method: export_method, xcconfig: xcconfig_filename)` to `gym(export_method: export_method, xcconfig: xcconfig_filename, export_options: {provisioningProfiles: {
			  "#{app_identifier}": "#{provisioning_profile_name}"
		  }})`

This allows us to deploy to hockey but unfortunately, now we can't run XCTests for the subprojects

2017-12-21 14:17:34.243054+0000 xctest[14669:292715] The bundle “XXXXTests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2017-12-21 14:17:34.244042+0000 xctest[14669:292715] (dlopen_preflight(../Library/Developer/Xcode/DerivedData/OurProject-efkkyzvsnlwkbiaqxcvqtsyaxbrb/Build/Products/Debug-iphonesimulator/XXXXTests.xctest/XXXXTests): no suitable image found.  Did find:
	../Library/Developer/Xcode/DerivedData/OurProject-efkkyzvsnlwkbiaqxcvqtsyaxbrb/Build/Products/Debug-iphonesimulator/XXXXTests.xctest/XXXXTests: required code signature missing for '../Library/Developer/Xcode/DerivedData/OurProject-efkkyzvsnlwkbiaqxcvqtsyaxbrb/Build/Products/Debug-iphonesimulator/XXXXTests.xctest/XXXXTests'
)

**Comment by maskedpear** [comment]
Hi @zacoid55 any update on this one?

**Comment by zacoid55** [comment]
Heya, @maskedpear - sorry about delay. I'm going to drag a couple of other people in on this. @NikolaKirev @Neil3079

**Comment by Neil3079** [comment]
@maskedpear what happens when you build and test using xcodebuild from the command line?

**Comment by maskedpear** [comment]
@Neil3079 This is what I see:
```
2018-01-25 11:07:27.794 xcodebuild[7493:123338] Error Domain=IDETestOperationsObserverErrorDomain Code=6 "Early unexpected exit, operation never finished bootstrapping - no restart will be attempted" UserInfo={NSLocalizedDescription=Early unexpected exit, operation never finished bootstrapping - no restart will be attempted}

Testing failed:
	Test target Tests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)
** TEST FAILED **
```

Please note, we started seeing these issues after migrating to Swift 4 (Xcode 9.0)

**Comment by Neil3079** [comment]
This definitely seems like an issue upgrading to Swift 4.0 then as xcodebuild is not related to the MasterFastfile. How is the project setup?

**Comment by maskedpear** [comment]
OK. I will try to explain our issue as well as possible. Since switching to Xcode 9 we started seeing this issue. We did migrate to Swift 4 at the same time. If that's a coincidence or not, I can't tell. Our large project, has few sub-projects (private projects we use in our Organization). When I do run, `deploy_to_hockey` for QA purposes, I get the error below:
```
[15:19:58]: ▸ === BUILD TARGET InternalTarget OF PROJECT InternalProject WITH CONFIGURATION Release ===
[15:19:58]: ▸ Check dependencies
[15:19:58]: ▸ Code Signing Error: InternalTarget does not support provisioning profiles. InternalTarget does not support provisioning profiles, but provisioning profile 'OUR_ENTERPRISE_PROV' has been manually specified. Set the provisioning profile value to "Automatic" in the build settings editor.
```
The only place we specify our Enterprise prov profile is inside `TAB.release.xcconfig` file. Inside Masterfile, under `_build_with_gym()` line 77 you see a reference of it. We think, that's what is causing the problem. When is executing `gym(export_method: export_method, xcconfig: xcconfig_filename)` it fails with the error above. I just can't see how we can bypass that because whatever we have under build settings, it gets overwritten.

**Comment by maskedpear** [comment]
@zacoid55 @Neil3079 Just a quick update with my findings.
I was playing around with the Fastfile setup last night and I think the issue is a combination of,
Xcode 9 + Cocoapods
Xcode 9 + fastlane + gym

First thing, I did copy the method `_build_with_gym()` locally so I can modify it. There's a known issue (as @zacoid55 mentioned in a previous comment) with Cocoapods and Xcode 9 where it shows prov profile for pods as `NO_SIGNING\`. However, I was struggling to understand why in our case wasn't showing that but our enterprise profile instead. 
So, after a few tries, I did remove the `xcconfig` parameter from the gym action and then started seeing the `NO_SIGNING\` warning. I went back to the project, change pods build setting to 'Automatic' and that warning went away. Now, I am looking for a way to set the provisioning profile to the app other than `xcconfig` (which I believe is the issue). 

I did try this https://docs.fastlane.tools/codesigning/xcode-project/#xcode-9-and-up

```
gym(export_method: export_method, export_options: {
      	provisioningProfiles: {
			  "#{app_identifier}" => "#{provisioning_profile_name}"
			}
		})
```

but bundle id is incorrect

```
+--------------------------------------------------------+--------------------------------------------------------+
|                                             Summary for gym 2.78.0                                              |
+--------------------------------------------------------+--------------------------------------------------------+
| export_method                                          | enterprise                                             |
| export_options.provisioningProfiles.com.bundle.id  | Enterprise                            |
| workspace                                              | ./Project.xcworkspace                               |
| destination                                            | generic/platform=iOS                                   |
| build_path                                             | ../Library/Developer/Xcode/Ar  |
| scheme                                                 | Scheme-Test                                          |
| clean                                                  | false                                                  |
| output_directory                                       | .                                                      |
| silent                                                 | false                                                  |
| codesigning_identity                                   | iPhone Distribution:         |
| skip_package_ipa                                       | false                                                  |
| buildlog_path                                          | ~/Library/Logs/gym                                     |
| skip_profile_detection                                 | false                                                  |
| xcode_path                                             | /Applications/Xcode.app                                |
+--------------------------------------------------------+--------------------------------------------------------+

[10:18:02]: ▸ Code Signing Error: Code signing is required for product type 'Application' in SDK 'iOS 11.2'
```

https://github.com/fastlane/fastlane/issues/9890

**Comment by Neil3079** [comment]
In xcode 9 and above you do need to set the profile using an export options plist. In our projects we add this plist as a file in a project and point fastlane at it with the following `GYM_EXPORT_OPTIONS=${PATH_TO_FILE}`. It is also necessary to define a Provfile for the project so gym will only apply this to the correct targets.

A Provfile is just a a file named Profile and will contain something like the following;

```
target 'My App target' do
  ENV['TAB_PROVISIONING_PROFILE']
end
```

**Comment by maskedpear** [comment]
@Neil3079 Thank you for the quick response. I will give that a try later today and let you know.
Could you please give some more info regarding Provfile as I haven't use it before. Where should that file exist and how Fastfile knows where to find it? Thanks

**Comment by Neil3079** [comment]
The `Provfile` was something we created in for the purpose of supporting app extensions (where multiple profiles are used) but it's also useful for solving this problem, it needs to live in the same directory as your fastfile. You can see in the code for the Master Fastfile how it is referenced and called

**Comment by maskedpear** [comment]
OK. We managed to resolve this issue. Huge thanks to @Neil3079 for his guidelines. We are now able to deploy to hockey and run all unit tests successfully.
However, the console still prints out
```
[13:16:26]: Couldn't automatically detect the provisioning profile mapping
[13:16:26]: Since Xcode 9 you need to provide an explicit mapping of what
[13:16:26]: provisioning profile to use for each target of your app
[13:16:26]: no implicit conversion of Symbol into Integer
```
Any idea how we can silence that?

**Comment by KaneCheshire** [comment]
I've been trying to solve that output myself but haven't come to a solution yet. I'm not too worried about it since builds are working but it would be nice to fix.

**Comment by KaneCheshire** [comment]
Can we close this issue now?

**Comment by maskedpear** [comment]
I am happy to close the issue. As @KaneCheshire would be nice to fix that output at some point.

**Comment by KaneCheshire** [comment]
Agreed! Thanks @maskedpear, let us know if there’s anything else we can do :)
